"""Add missing models and fields from drawio requirements

Revision ID: 11a0c3639303
Revises: 
Create Date: 2025-11-06 10:58:57.910692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11a0c3639303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('student_id', sa.String(), nullable=False))
    op.add_column('complaints', sa.Column('complaint_photos', sa.String(length=1000), nullable=True))
    op.alter_column('complaints', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('complaints', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('complaints', 'hostel_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('hostels', sa.Column('hostel_name', sa.String(length=255), nullable=False))
    op.add_column('hostels', sa.Column('hostel_type', sa.Enum('BOYS', 'GIRLS', 'CO_ED', 'PG', 'HOSTEL', name='hosteltype'), nullable=False))
    op.add_column('hostels', sa.Column('rules', sa.Text(), nullable=True))
    op.add_column('hostels', sa.Column('check_in_time', sa.Time(), nullable=True))
    op.add_column('hostels', sa.Column('check_out_time', sa.Time(), nullable=True))
    op.add_column('hostels', sa.Column('total_beds', sa.Integer(), nullable=False))
    op.add_column('hostels', sa.Column('occupancy', sa.Integer(), nullable=False))
    op.add_column('hostels', sa.Column('revenue', sa.Float(), nullable=False))
    op.add_column('hostels', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('hostels', sa.Column('visibility', sa.String(length=50), nullable=False))
    op.add_column('hostels', sa.Column('featured', sa.Boolean(), nullable=True))
    op.add_column('hostels', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('hostels', sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hostels', sa.Column('booking_requests', sa.Integer(), nullable=True))
    op.add_column('hostels', sa.Column('maintenance_requests', sa.Integer(), nullable=True))
    op.alter_column('hostels', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('hostels', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('hostels', 'pincode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('hostels', 'price_per_month',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('hostels', 'total_rooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hostels', 'available_rooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('hostels', 'name')
    op.add_column('payments', sa.Column('student_id', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('payment_due_date', sa.String(), nullable=True))
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'hostel_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'fee_type',
               existing_type=postgresql.ENUM('RENT', 'SECURITY_DEPOSIT', 'MAINTENANCE', 'ELECTRICITY', 'WATER', 'MESS', 'LAUNDRY', 'OTHER', name='feetype'),
               nullable=True)
    op.add_column('referrals', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('referrals', sa.Column('reward_amount', sa.Float(), nullable=False))
    op.add_column('referrals', sa.Column('completed_at', sa.String(), nullable=True))
    op.drop_constraint(op.f('referrals_referrer_id_fkey'), 'referrals', type_='foreignkey')
    op.add_column('reviews', sa.Column('student_id', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('review_rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('review_category', sa.Enum('ACCOMMODATION', 'FOOD', 'STAFF', 'FACILITIES', 'CLEANLINESS', 'OVERALL', name='reviewcategory'), nullable=False))
    op.alter_column('reviews', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reviews', 'overall_rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('rooms', sa.Column('room_capacity', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('monthly_price', sa.Float(), nullable=False))
    op.add_column('rooms', sa.Column('quarterly_price', sa.Float(), nullable=False))
    op.add_column('rooms', sa.Column('annual_price', sa.Float(), nullable=False))
    op.add_column('rooms', sa.Column('availability', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('amenities', sa.String(length=1000), nullable=True))
    op.add_column('rooms', sa.Column('maintenance_status', sa.Enum('GOOD', 'NEEDS_REPAIR', 'UNDER_MAINTENANCE', 'OUT_OF_ORDER', name='maintenancestatus'), nullable=False))
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'price_per_month',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('users', sa.Column('student_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('hostel_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('blood_group', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('guardian_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('guardian_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'guardian_phone')
    op.drop_column('users', 'guardian_name')
    op.drop_column('users', 'blood_group')
    op.drop_column('users', 'hostel_code')
    op.drop_column('users', 'student_id')
    op.alter_column('rooms', 'price_per_month',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rooms', 'maintenance_status')
    op.drop_column('rooms', 'amenities')
    op.drop_column('rooms', 'availability')
    op.drop_column('rooms', 'annual_price')
    op.drop_column('rooms', 'quarterly_price')
    op.drop_column('rooms', 'monthly_price')
    op.drop_column('rooms', 'room_capacity')
    op.alter_column('reviews', 'overall_rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reviews', 'review_category')
    op.drop_column('reviews', 'review_rating')
    op.drop_column('reviews', 'student_id')
    op.create_foreign_key(op.f('referrals_referrer_id_fkey'), 'referrals', 'users', ['referrer_id'], ['id'])
    op.drop_column('referrals', 'completed_at')
    op.drop_column('referrals', 'reward_amount')
    op.drop_column('referrals', 'status')
    op.alter_column('payments', 'fee_type',
               existing_type=postgresql.ENUM('RENT', 'SECURITY_DEPOSIT', 'MAINTENANCE', 'ELECTRICITY', 'WATER', 'MESS', 'LAUNDRY', 'OTHER', name='feetype'),
               nullable=False)
    op.alter_column('payments', 'hostel_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payments', 'payment_due_date')
    op.drop_column('payments', 'student_id')
    op.add_column('hostels', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('hostels', 'available_rooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hostels', 'total_rooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hostels', 'price_per_month',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('hostels', 'pincode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('hostels', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('hostels', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('hostels', 'maintenance_requests')
    op.drop_column('hostels', 'booking_requests')
    op.drop_column('hostels', 'last_accessed')
    op.drop_column('hostels', 'is_favorite')
    op.drop_column('hostels', 'featured')
    op.drop_column('hostels', 'visibility')
    op.drop_column('hostels', 'status')
    op.drop_column('hostels', 'revenue')
    op.drop_column('hostels', 'occupancy')
    op.drop_column('hostels', 'total_beds')
    op.drop_column('hostels', 'check_out_time')
    op.drop_column('hostels', 'check_in_time')
    op.drop_column('hostels', 'rules')
    op.drop_column('hostels', 'hostel_type')
    op.drop_column('hostels', 'hostel_name')
    op.alter_column('complaints', 'hostel_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('complaints', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('complaints', 'priority',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'),
               existing_nullable=False)
    op.drop_column('complaints', 'complaint_photos')
    op.drop_column('complaints', 'student_id')
    # ### end Alembic commands ###