"""Fix referrer_id foreign key constraint

Revision ID: 6486735efe5f
Revises: 9955ec964cdd
Create Date: 2025-11-06 11:25:24.931776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6486735efe5f'
down_revision = '9955ec964cdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'referrals', 'users', ['referrer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    # ### end Alembic commands ###