"""Restore attendance model for supervisor operations

Revision ID: 9955ec964cdd
Revises: a98242b6a482
Create Date: 2025-11-06 11:14:25.413622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9955ec964cdd'
down_revision = 'a98242b6a482'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hostel_id', sa.String(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('attendance_status', sa.String(length=50), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leave_type', sa.String(length=50), nullable=True),
    sa.Column('leave_reason', sa.Text(), nullable=True),
    sa.Column('leave_approved_by', sa.String(), nullable=True),
    sa.Column('leave_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supervisor_remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###