"""Add new entity tables from drawio

Revision ID: bf0256c25190
Revises: 11a0c3639303
Create Date: 2025-11-06 10:59:42.823096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0256c25190'
down_revision = '11a0c3639303'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###