"""Remove unnecessary features not in drawio

Revision ID: a98242b6a482
Revises: bf0256c25190
Create Date: 2025-11-06 11:09:24.461724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a98242b6a482'
down_revision = 'bf0256c25190'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('subscriptions')
    op.drop_table('mess_menus')
    op.drop_column('complaints', 'room_number')
    op.drop_column('complaints', 'resolved_at')
    op.drop_column('complaints', 'assigned_to')
    op.drop_column('complaints', 'resolution_notes')
    op.drop_column('complaints', 'user_feedback')
    op.drop_column('complaints', 'resolution_attachments')
    op.drop_column('complaints', 'user_rating')
    op.drop_column('complaints', 'location_details')
    op.drop_column('complaints', 'closed_at')
    op.drop_column('complaints', 'attachments')
    op.drop_column('hostels', 'total_reviews')
    op.drop_column('hostels', 'total_rooms')
    op.drop_column('hostels', 'latitude')
    op.drop_column('hostels', 'longitude')
    op.drop_column('hostels', 'is_verified')
    op.drop_column('hostels', 'rating')
    op.drop_column('hostels', 'images')
    op.drop_column('hostels', 'price_per_month')
    op.drop_column('hostels', 'contact_person')
    op.drop_column('hostels', 'available_rooms')
    op.drop_column('payments', 'gateway_response')
    op.drop_column('payments', 'late_fee')
    op.drop_column('payments', 'description')
    op.drop_column('payments', 'notes')
    op.drop_column('payments', 'gateway_transaction_id')
    op.drop_column('payments', 'discount')
    op.drop_column('payments', 'receipt_url')
    op.drop_column('payments', 'due_date')
    op.drop_column('payments', 'paid_date')
    op.drop_column('referrals', 'booking_date')
    op.drop_column('referrals', 'referrer_reward_claimed')
    op.drop_column('referrals', 'is_successful')
    op.drop_column('referrals', 'referrer_reward_amount')
    op.drop_column('referrals', 'booking_completed')
    op.drop_column('referrals', 'referred_signup_date')
    op.drop_column('referrals', 'campaign_id')
    op.drop_column('referrals', 'referred_reward_claimed')
    op.drop_column('referrals', 'signup_completed')
    op.drop_column('referrals', 'referred_reward_amount')
    op.drop_column('referrals', 'reward_claimed_date')
    op.drop_column('referrals', 'campaign_name')
    op.drop_column('reviews', 'helpful_count')
    op.drop_column('reviews', 'is_approved')
    op.drop_column('reviews', 'is_anonymous')
    op.drop_column('reviews', 'moderation_notes')
    op.drop_column('reviews', 'is_verified')
    op.drop_column('reviews', 'hostel_response')
    op.drop_column('reviews', 'location_rating')
    op.drop_column('reviews', 'hostel_response_date')
    op.drop_column('reviews', 'stay_duration_months')
    op.drop_column('reviews', 'not_helpful_count')
    op.drop_column('reviews', 'is_flagged')
    op.drop_column('reviews', 'value_for_money_rating')
    op.drop_column('reviews', 'images')
    op.drop_column('reviews', 'title')
    op.drop_column('reviews', 'staff_rating')
    op.drop_column('reviews', 'facilities_rating')
    op.drop_column('reviews', 'food_rating')
    op.drop_column('reviews', 'cleanliness_rating')
    op.drop_column('rooms', 'has_wifi')
    op.drop_column('rooms', 'is_under_maintenance')
    op.drop_column('rooms', 'floor_number')
    op.drop_column('rooms', 'area_sqft')
    op.drop_column('rooms', 'has_ac')
    op.drop_column('rooms', 'maintenance_notes')
    op.drop_column('rooms', 'images')
    op.drop_column('rooms', 'has_balcony')
    op.drop_column('rooms', 'has_attached_bathroom')
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'emergency_contact_name')
    op.drop_column('users', 'address')
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('emergency_contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_reset_token')
    op.add_column('rooms', sa.Column('has_attached_bathroom', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('has_balcony', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('images', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('maintenance_notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('has_ac', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('area_sqft', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('floor_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('is_under_maintenance', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('has_wifi', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('cleanliness_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('food_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('facilities_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('staff_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('value_for_money_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('is_flagged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('not_helpful_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('stay_duration_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('hostel_response_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('location_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('hostel_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('moderation_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('helpful_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('campaign_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('reward_claimed_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('referred_reward_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('signup_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('referred_reward_claimed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('referred_signup_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('booking_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('referrer_reward_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('is_successful', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('referrer_reward_claimed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('booking_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('paid_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('receipt_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('gateway_transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('late_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('gateway_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('available_rooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('contact_person', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('price_per_month', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('total_rooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('total_reviews', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('attachments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('location_details', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('user_rating', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('resolution_attachments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('user_feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('room_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('mess_menus',
    sa.Column('hostel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), autoincrement=False, nullable=False),
    sa.Column('meal_type', postgresql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACKS', name='mealtype'), autoincrement=False, nullable=False),
    sa.Column('menu_items', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_included_in_plan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('calories', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nutritional_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_vegetarian', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_vegan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_gluten_free', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('contains_dairy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('contains_nuts', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('serving_time_start', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('serving_time_end', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('chef_special', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('seasonal_item', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], name=op.f('mess_menus_hostel_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mess_menus_pkey'))
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subscription_type', postgresql.ENUM('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', name='subscriptiontype'), autoincrement=False, nullable=False),
    sa.Column('subscription_status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monthly_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auto_renewal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('renewal_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('includes_mess', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('includes_laundry', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('includes_wifi', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('includes_housekeeping', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('includes_gym', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('mess_meals_included', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('laundry_pieces_included', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('wifi_data_limit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refund_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('terms_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    op.create_table('attendance',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hostel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('attendance_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('attendance_status', postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('check_out_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('check_in_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('check_out_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('breakfast_attended', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('lunch_attended', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('dinner_attended', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('leave_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('leave_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('leave_approved_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('leave_approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('late_arrival_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('late_arrival_approved', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('supervisor_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biometric_data', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rfid_card_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], name=op.f('attendance_hostel_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendance_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey'))
    )
    # ### end Alembic commands ###